version: "3"
services:
        app:
                image: node:latest
                volumes: 
                        - ./app:/opt/app
                command: node/opt/app/app.js
        nginx:
                image: nginx:latest
                ports:
                        - "1313:8080"
                volumes:
                        - ./nginx/1b.conf:/etc?nginx/conf.d/1b.conf
                depends_on:
                        - app

